"""
Replace the stale "Step 1 sanity checkpoint" Detection Overlay section in
the already-built src/dashboard/output/index.html with the 10 real
epoch-39 demo examples generated by scripts/generate_demo_assets.py.

Does NOT touch the drift map, ranked-suspects panel, or the geo-strip
geometric-characterization panel below the overlay -- those are real,
working, and out of scope. Does NOT re-run the dashboard generator
(src/dashboard/build_dashboard.py) -- that would re-hit live GFW/ERA5 data
paths we don't want to touch tonight. This is a surgical string replacement
on the static HTML output only.

Reuses the file's own existing CSS classes/colors (.geo-cell, .geo-cells,
--navy-*, --fog-dim, --paper, --teal/--alert/--amber) -- new CSS added is
purely additive (new class names), nothing existing is modified.

Usage:
    venv\\Scripts\\python.exe scripts\\integrate_demo_into_dashboard.py
"""

from __future__ import annotations

import base64
import json
from pathlib import Path

REPO_ROOT = Path(__file__).resolve().parent.parent
DASHBOARD_HTML = REPO_ROOT / "src" / "dashboard" / "output" / "index.html"
DEMO_DIR = REPO_ROOT / "web" / "public" / "demo"

NEW_CSS = """
    .demo-grid{display:flex;flex-direction:column;gap:14px;padding:0 20px 18px;}
    .demo-row{background:var(--navy-app);border:1px solid var(--line-soft);border-radius:10px;padding:12px 14px;display:flex;gap:16px;flex-wrap:wrap;align-items:flex-start;}
    .demo-imgs{display:flex;gap:8px;flex:0 0 auto;}
    .demo-imgs figure{margin:0;width:120px;}
    .demo-imgs img{width:120px;height:120px;object-fit:cover;display:block;border-radius:6px;border:1px solid var(--line-soft);background:#000;}
    .demo-imgs figcaption{font-size:10px;color:var(--fog-dim);text-align:center;margin-top:3px;}
    .demo-meta{flex:1 1 220px;min-width:220px;}
    .demo-meta-head{display:flex;align-items:center;gap:8px;margin-bottom:8px;}
    .demo-label{font-family:'Chivo',system-ui,sans-serif;font-weight:700;font-size:12px;color:var(--paper);}
    .demo-tag{font-size:10px;font-weight:700;text-transform:uppercase;letter-spacing:.03em;padding:2px 7px;border-radius:999px;}
    .demo-tag.oil{background:var(--alert-soft);color:#ff9d9a;}
    .demo-tag.lookalike{background:var(--amber-soft);color:var(--amber-bright);}
    .demo-tag.no_oil{background:var(--teal-soft);color:var(--teal-bright);}
    .demo-stats{display:grid;grid-template-columns:repeat(3,1fr);gap:6px 14px;font-size:11px;}
    .demo-stats .stat-label{color:var(--fog-dim);}
    .demo-stats .stat-value{color:var(--paper);font-weight:600;}
"""


def b64(path: Path) -> str:
    return base64.b64encode(path.read_bytes()).decode("ascii")


def build_row_html(metrics: dict) -> str:
    image_id = metrics["image_id"]
    label = metrics["label"]
    raw_b64 = b64(DEMO_DIR / f"{image_id}_raw.png")
    gt_b64 = b64(DEMO_DIR / f"{image_id}_gt.png")
    pred_b64 = b64(DEMO_DIR / f"{image_id}_pred.png")

    return f"""
      <div class="demo-row">
        <div class="demo-imgs">
          <figure><img src="data:image/png;base64,{raw_b64}"><figcaption>Input (SAR)</figcaption></figure>
          <figure><img src="data:image/png;base64,{gt_b64}"><figcaption>Ground truth</figcaption></figure>
          <figure><img src="data:image/png;base64,{pred_b64}"><figcaption>Prediction</figcaption></figure>
        </div>
        <div class="demo-meta">
          <div class="demo-meta-head">
            <span class="demo-label">{image_id}</span>
            <span class="demo-tag {label}">{label}</span>
          </div>
          <div class="demo-stats">
            <div><div class="stat-label">IoU</div><div class="stat-value">{metrics['iou']:.3f}</div></div>
            <div><div class="stat-label">Precision</div><div class="stat-value">{metrics['precision']:.3f}</div></div>
            <div><div class="stat-label">Recall</div><div class="stat-value">{metrics['recall']:.3f}</div></div>
            <div><div class="stat-label">Predicted oil</div><div class="stat-value">{metrics['predicted_oil_pct']:.1f}%</div></div>
            <div><div class="stat-label">True oil</div><div class="stat-value">{metrics['true_oil_pct']:.1f}%</div></div>
            <div><div class="stat-label">Dice</div><div class="stat-value">{metrics['dice']:.3f}</div></div>
          </div>
        </div>
      </div>"""


def main() -> None:
    summary = json.loads((DEMO_DIR / "summary.json").read_text())
    baseline = summary["baseline_oil_tiles_only"]

    rows_html = "\n".join(build_row_html(m) for m in summary["images"])
    demo_grid_html = f'    <div class="demo-grid">{rows_html}\n    </div>\n'

    content = DASHBOARD_HTML.read_text(encoding="utf-8")
    original_len = len(content)

    # 1. Replace the single stale overlay <img> line with the new demo grid.
    img_start = content.find('<img class="overlay-img" src="data:image/png;base64,')
    if img_start == -1:
        raise RuntimeError("Could not find the existing overlay-img tag -- aborting without modifying the file.")
    img_end = content.find('">', img_start) + len('">')
    content = content[:img_start] + demo_grid_html.strip() + content[img_end:]

    # 2. Replace the stale panel-sub text with real epoch-39 numbers.
    old_sub = ("Inference plumbing (load checkpoint -> predict -> overlay) built and run on a "
               "real Zenodo tile below -- using the Step 1 SANITY checkpoint (trained on 4 "
               "bbox-pseudo-mask images), not a real trained model. Real training pending "
               "Zenodo Part II/III download + extraction.")
    baseline_threshold = summary["threshold"]
    new_sub = (f"Epoch-39 baseline checkpoint (real training run), threshold {baseline_threshold} -- "
               f"real oil-tiles-only IoU {baseline['iou']:.4f}, precision {baseline['precision']:.3f}, "
               f"recall {baseline['recall']:.3f} on the validation set (see docs/metric_audit.md). "
               f"{len(summary['images'])} real validation examples shown below: input SAR, real ground truth, and the model's actual prediction.")
    if old_sub not in content:
        raise RuntimeError("Could not find the existing panel-sub text -- aborting without further modification.")
    content = content.replace(old_sub, new_sub, 1)

    # 3. Update the footer note.
    old_footer_fragment = "detection overlay uses a non-final sanity checkpoint"
    new_footer_fragment = f"detection overlay uses the real epoch-39 checkpoint (oil IoU {baseline['iou']:.4f})"
    if old_footer_fragment not in content:
        raise RuntimeError("Could not find the existing footer text -- aborting without further modification.")
    content = content.replace(old_footer_fragment, new_footer_fragment, 1)

    # 4. Insert new (purely additive) CSS just before </style>.
    style_close = content.find("</style>")
    if style_close == -1:
        raise RuntimeError("Could not find </style> -- aborting without further modification.")
    content = content[:style_close] + NEW_CSS + content[style_close:]

    DASHBOARD_HTML.write_text(content, encoding="utf-8")
    print(f"wrote {DASHBOARD_HTML} ({original_len} -> {len(content)} bytes)")
    print(f"embedded {len(summary['images'])} real examples from {DEMO_DIR}")


if __name__ == "__main__":
    main()
